name: pajakpro
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^3.0.0

flutter: 
  uses-material-design: true  
  assets:
    - assets/logo/google.png
    - assets/logo/pajakpro-logo.jpeg
    - assets/logo/pajakpro-logo2.jpeg
    - assets/logo/pajakpro-logo-nobg.png
    - assets/logo/pajakpro-logo2-nobg.png
    - assets/logo/google.png
    - assets/logo/google.png
    - assets/logo/google.png
    - assets/icons/bea-perolehan-hak-atas-tanah-dan-bangunan.png
    - assets/icons/pajak-barang-dan-jasa.png
    - assets/icons/pajak-bumi-dan-bangunan.png
    - assets/icons/pajak-daerah.png
    - assets/icons/pajak-kendaraan-bermotor.png
    - assets/icons/pajak-penghasilan.png
    - assets/icons/pajak-penjualan-atas-barang-mewah.png
    - assets/icons/pajak-pertambahan-nilai.png
    


  
  

  
  

  
  
  
  
  
  
  
  
  
 
  

